### ISSUE TITLE
UDP port

### ISSUE THREAD

**Issue by slavkoja** [Matte23/server-status-page#1]
**Is your feature request related to a problem? Please describe.**
Current Port test only tests TCP ports

**Describe the solution you'd like**
Please, add UDP port test

**Additional context**
I am not PHP man, but IMO it can be achieved by adding optional option e.g. "type", which will default (when unset) to "tcp" and will use current code, and when setting to "udp", there will be alternative (UDP) fsckopen command invoked.

**Comment by Matte23** [comment]
Thanks for this feature request. I'm implementing this now. fsckopen can set to use UDP by prefixing "udp://" to the URL, so it will be easy to implement this.

**Comment by Matte23** [comment]
Sadly this can't be implemented, due the nature of UDP. When connecting and sending data to an UDP port, the server doesn't respond with an acknowledgement message, so it's impossible to tell if the port is open (in my test, I haven't got any errors even if I was connecting to a non existing server). Maybe it is still possible to implement a test for your specific case if the protocol implemented over UDP is expected to send a response given a determinate request. Feel free to ask for help

**Comment by slavkoja** [comment]
IMO, you abandon it too quickly. You are right, scanning UDP port is tricky, but possible, as you can read on [nmap site](https://nmap.org/book/scan-methods-udp-scan.html). In status page case it is more simple as real scan, because we can consider port as opened, if no ICMP Port unreachable arrives. Testing blocked port or unreachable machine will provide false true result, but this can be documented as limitation of this check and IMO is acceptable as better than nothing.

Finally i found [PHP article](https://www.sitepoint.com/udp-portscanning-php/), where is UDP scan implemented by ``fsockopen``, which i adapted to command line script (for easy testing):
```php
<?php
$timeout = 100000;
$rip = $argv[1];
$port = $argv[2];

$sock = fsockopen("udp://". $rip, $port, $errno, $errstr, 0);
if (!$sock) {
    die("Error: $errno : $errstr\n");
}
socket_set_timeout ($sock, 0, $timeout);

$write = fwrite($sock, "x00");
if (!$write) {
    die("Error writing to port\n");
}
$tstart = microtime(TRUE);
$header = fread($sock, 1);
$tdiff = microtime(TRUE) - $tstart;

fclose($sock);

if ($tdiff >= $timeout / 1000000) {
    echo "open/filtered\n";
} else {
    echo "closed $tdiff\n";
}
```
Provide it IP/name and port as arguments and see result (tweak timeout value, if needed), e.g.:
```
php udptest.php IP.AD.RE.SS port
```

**Comment by Matte23** [comment]
You're right, I'm giving a look at this

**Comment by Matte23** [comment]
I've implemented the UDP port check, thanks to your support!
Check out the [`Test/Port.php`](https://github.com/Matte23/server-status-page/blob/master/tests/Port.php) file. As you said, the UDP port check is tricky and doesn't always work. You can now use UDP by adding `"type": "udp",` to your configuration file. I've also added a configuration entry to change the timeout.

**Comment by slavkoja** [comment]
I consider timeout in seconds as big. Do not forget, that success test will always take this timeout secs (10 s in your code), which is too long, especially when one will have more UDP tests. I used microseconds for it, to minimize success test duration.

When i test it with remote (my domain hosting, mote than 12 hops) DNS server, i got ICMP response within 60 ms. Then i suggest to make config option in ms and then recalculate it into microsec.

**Comment by Matte23** [comment]
Good idea, I'm implementing it now

**Comment by Matte23** [comment]
Done

**Comment by slavkoja** [comment]
I tried current master and you have mistake in ``$time_delta`` check -- you leave the 1000000 in division -- thus it do not recognize errors. When i fix it to 1000, it works as expected. Only wiki page stays on 10 sec timeout (my English is too bad to fix it) ;-) 

Setting the timeout value is confusing. The port number in JSON can be string (no type test), but timeout have to be integer. I suggest to make them equal, both must be strings or both can be string or integer.

From my point of view, i suggest to change default timeout to 100 ms, to one need to change it only if needed more time to get response on slow links. Then, by default, the check will be quicker.

**Comment by Matte23** [comment]
Ops, sorry for the silly mistake. Regarding the wiki, I was waiting for a response before editing (I'll fix it now anyway). You're right, I still have to enforce type check. I don't know if 100 ms is too short, I'll push it anyway and if I'll receive lots of complaints I will raise it (although this project is still used only by a few people :-) ). Try with the new file on master branch

**Comment by slavkoja** [comment]
do not worry, we are all doing mistakes ;-)

About timeout. AFAIK, here is not one good/proper value. All depends on network. If the default will be too short, many people will need to define custom value to not get false positives. If value will be too long, many people will need to define custom value to shorten positive tests duration.

When i think about it now. Great will be one global value, where anybody can customize it for own network connection and all UDP test in one place. And allowing to set it in particular test will allow solve problem by test. And all with minimal effort. Consider situation, where someone uses it for localhost services -- 1 ms will be enough. In my LAN the 10 ms is more than needed (in really 1 ms is enough too). For WAN access -- nobody know and 1000 ms can be too little...

**Comment by Matte23** [comment]
I would extend this feature to all test by providing an entry to set default values in config.json, so I can keep the modularity of the implementation while providing a place to set default values (es timeout) for every test. To keep issue management ordinated, I've created a new issue #3 so I can close this one regarding UDP
